stages:
- build
- deploy
- release

build:
  stage: build
  script:
    - make -f fabric.mk package
  environment:
    name: snap

deploy_snap:
  stage: deploy
  script:
    - sudo -u fabric fab snap deploy:qgis_cadastre,force=true
  environment:
    name: snap

release_prod:
  stage: release
  script:
    - sudo -u fabric fab prod release:qgis_cadastre
  environment:
    name: production
  when: manual
  only:
    - tags
